# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Server CI

on:
  push:
    branches: [develop, master]
    paths:
      - "server/**"
  pull_request:
    branches: [develop, master]
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      working-directory: ./server
      JWT_SECRET: testasdf
      TYPEORM_HOST: localhost
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_SYNCHRONIZE: false
      TYPEORM_LOGGING: true

    steps:
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: galois
          postgresql user: postgres
          postgresql password: postgres

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        working-directory: server
        run: yarn

      - name: Initialize DB schema
        working-directory: server
        run: yarn typeorm:cli schema:sync

      - name: Run test
        working-directory: server
        run: yarn test:ci
