# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Storybook

on:
  push:
    branches: [develop]
    paths:
      - "client/**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      working-directory: ./client
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"

      - name: Build
        working-directory: client
        run: |
          yarn
          yarn build-storybook -o ./storybook-build

      - name: Upload to storybook branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: storybook
          publish_dir: ./client/storybook-build
          github_token: ${{ secrets.GITHUB_TOKEN }}
